from fastapi import FastAPI, Depends, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from pydantic import BaseModel
from backend.services.ocr_service import extract_text_from_image
# Import our database setup and models
from backend.database import engine, get_db
from backend.models import schemas

# Create database tables
schemas.Base.metadata.create_all(bind=engine)

app = FastAPI(title="MathSolve AI Backend")

# Setup CORS so the Streamlit frontend can communicate with FastAPI
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Allows all origins for local hackathon testing
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Pydantic schema for incoming text queries
class QuestionRequest(BaseModel):
    session_id: str
    text: str

@app.get("/")
def read_root():
    return {"status": "MathSolve AI API is running"}

@app.post("/upload-image/")
async def upload_image(file: UploadFile = File(...)):
    """
    Receives a photo of a handwritten question and extracts text using OCR.
    """
    if not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="File provided is not an image.")
    
    # Read the file into bytes
    image_bytes = await file.read()
    
    # Run the real OCR service
    extracted_text = extract_text_from_image(image_bytes)
    
    return {
        "filename": file.filename, 
        "extracted_text": extracted_text
    }



@app.post("/solve/")
def solve_question(request: QuestionRequest, db: Session = Depends(get_db)):
    """
    Takes a text question, runs it through RAG + Gemma 4, and saves to DB.
    """
    # TODO: Pass request.text to rag_service.py to get the real solution
    mock_solution = "Step 1: Recognize this is a standard trigonometric limit.\nStep 2: The limit of sin(x)/x as x approaches 0 is 1."
    
    # Save the interaction to the database for the progress dashboard
    new_history = schemas.QuestionHistory(
        session_id=request.session_id,
        original_text=request.text,
        solution_text=mock_solution,
        topic_tag="Limits", # This could be dynamically generated by the LLM later
        difficulty_level="Medium" 
    )
    db.add(new_history)
    db.commit()
    db.refresh(new_history)
    
    return {
        "question_id": new_history.id,
        "solution": new_history.solution_text,
        "topic": new_history.topic_tag
    }